module.exports =  {
    PRIZE_POOL: 100,
    SECRET: 'kui',
    BANK_ACCOUNT_CARD: '5432 1234 5432 5678',
    CUSTOMER_ROLE: 0,
    CREATIVE_ROLE: 1,
    MODERATOR_ROLE: 2,
    ENTRY_REJECTED: 'rejected',
    ENTRY_CONFIRMED: 'confirmed',
    ENTRY_WINNER: 'winner',
    NAME_TYPE: 'Name',
    LOGO_TYPE: 'Logo',
    TAGLINE_TYPE: 'Tagline',
    ROLE_RECEIVER: 'receiver',
    ROLE_SENDER: 'sender',
};
