export default {
  SET_ARRAY_ORDER: "SET_ARRAY_ORDER",
  GET_ARRAY_ORDER: "GET_ARRAY_ORDER",
  COLLECT_FORM_DATA: "COLLECT_FORM_DATA",
  FORM_DATA_SET: "FORM_DATA_SET",
  FORM_DATA_CLEAR: "FORM_DATA_CLEAR",

  GET_SELECTS: "GET_SELECTS",
  GET_SELECTS_REQUEST: "GET_SELECTS_REQUEST",
  GET_SELECTS_RESPONSE: "GET_SELECTS_RESPONSE",
  API_ERROR: "API_ERROR",

  USER_REGISTER: "USER_REGISTER",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_AUTH: "USER_AUTH",
  USER_CLEAN: "USER_CLEAN",

  USER_REQUEST: "USER_REQUEST",
  USER_RESPONSE: "USER_RESPONSE",
  USER_ERROR: "USERS_ERROR",

  CHECKOUT: 'CHECKOUT',
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_RESPONSE: 'CHECKOUT_RESPONSE',
  CHECKOUT_ERROR: 'CHECKOUT_ERROR',

  GET_CONTEST_BY_ID: 'GET_CONTESTS_BY_ID',
  GET_CONTEST_BY_ID_REQUEST: 'GET_CONTESTS_BY_ID_REQUEST',
  GET_CONTEST_BY_ID_RESPONSE: 'GET_CONTESTS_BY_ID_RESPONSE',

  GET_CUSTOMER_CONTESTS: 'GET_CUSTOMER_CONTESTS',
  GET_CUSTOMER_CONTESTS_REQUEST: 'GET_CUSTOMER_CONTESTS_REQUEST',
  GET_CUSTOMER_CONTESTS_RESPONSE: 'GET_CUSTOMER_CONTESTS_RESPONSE',
  GET_CUSTOMER_CONTESTS_ERROR: 'GET_CUSTOMER_CONTESTS_ERROR',
  GET_ALL_CONTESTS: "GET_ALL_CONTESTS",
  UPDATE_CONTEST: "UPDATE_CONTEST",
  UPDATE_CONTEST_RESPONSE: "UPDATE_CONTEST_RESPONSE",

  CREATE_ENTRY: "CREATE_ENTRY",
  REJECT_ENTRY: "REJECT_ENTRY",
  SET_ENTRY_WINNER: "SET_ENTRY_WINNER",

  ENTRY_REQUEST: "ENTRY_REQUEST",
  ENTRY_CREATE_RESPONSE: "ENTRY_CREATE_RESPONSE",
  ENTRY_WIN_RESPONSE: "ENTRY_WIN_RESPONSE",
  ENTRY_REJECT_RESPONSE: "ENTRY_REJECT_RESPONSE",
  ENTRY_ERROR: "ENTRY_ERROR",

  EDIT_USER_PROFILE: "EDIT_USER_PROFILE",
  EDIT_PROFILE_REQUEST: "EDIT_PROFILE_REQUEST",
  EDIT_PROFILE_RESPONSE: "EDIT_PROFILE_RESPONSE",
  EDIT_PROFILE_ERROR: "EDIT_PROFILE_ERROR",
}
