export default {
  TEST_ACTION: "TEST_ACTION",
  // USERS_REQUEST: "USERS_REQUEST",
  // USERS_RESPONSE: "USERS_RESPONSE",
  // USERS_ERROR: "USERS_ERROR",

  // GET_USER_PROFILE: "GET_USER_PROFILE",
  // USER_PROFILE_RESPONSE: "USER_PROFILE_RESPONSE",
  // USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",

  SET_ARRAY_ORDER: "SET_ARRAY_ORDER",
  GET_ARRAY_ORDER: "GET_ARRAY_ORDER",
  COLLECT_FORM_DATA: "COLLECT_FORM_DATA",

  GET_SELECTS: "GET_SELECTS",
  SET_SELECTS: "SET_SELECTS",
  API_ERROR: "API_ERROR",

  USER_REGISTER: "USER_REGISTER",
  USER_LOGIN: "USER_LOGIN",
  USER_AUTH: "USER_AUTH",
  USER_REQUEST: "USER_REQUEST",
  USER_RESPONSE: "USER_RESPONSE",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ERROR: "USERS_ERROR",

  CHECKOUT: 'CHECKOUT',
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_RESPONSE: 'CHECKOUT_RESPONSE',
  CHECKOUT_ERROR: 'CHECKOUT_ERROR',

  GET_CONTEST_BY_ID: 'GET_CONTESTS_BY_ID',
  GET_CONTEST_BY_ID_REQUEST: 'GET_CONTESTS_BY_ID_REQUEST',
  GET_CONTEST_BY_ID_RESPONSE: 'GET_CONTESTS_BY_ID_RESPONSE',

  GET_CUSTOMER_CONTESTS: 'GET_CUSTOMER_CONTESTS',
  GET_CUSTOMER_CONTESTS_REQUEST: 'GET_CUSTOMER_CONTESTS_REQUEST',
  GET_CUSTOMER_CONTESTS_RESPONSE: 'GET_CUSTOMER_CONTESTS_RESPONSE',
  GET_CUSTOMER_CONTESTS_ERROR: 'GET_CUSTOMER_CONTESTS_ERROR',

  GET_ALL_CONTESTS: "GET_ALL_CONTESTS"

}